// Sourced from https://www.cs.cmu.edu/~biglou/resources/bad-words.txt
export const profanitySet = new Set([
  'abbo', 'abo', 'abuse', 'addict', 'addicts', 'adult', 'africa', 'african', 'alla',
  'allah', 'alligatorbait', 'amateur', 'anal', 'analannie', 'analsex', 'angie',
  'angry', 'anus', 'arab', 'arabs', 'areola', 'argie', 'arouse', 'arse', 'arsehole',
  'asian', 'ass', 'assassin', 'asses', 'assfuck', 'assfucker', 'asshole', 'assholes',
  'assmaster', 'assmunch', 'asswipe', 'attack', 'australian', 'babe', 'babes', 'baby',
  'ball', 'balls', 'banging', 'barelylegal', 'barf', 'barface', 'bastard', 'beast',
  'beastality', 'beastial', 'beastiality', 'beatoff', 'beat-off', 'beatyourmeat',
  'bestial', 'bestiality', 'bi', 'biatch', 'bible', 'bi-curious', 'bigass', 'bigbastard',
  'bigbutt', 'bisexual', 'bitch', 'bitcher', 'bitches', 'bitching', 'biteme', 'black',
  'blacks', 'blind', 'blow', 'blowjob', 'blowjobs', 'bluegum', 'blue-gum', 'bod',
  'bodily', 'bondage', 'boner', 'boob', 'boobies', 'boobs', 'booby', 'boody', 'boom',
  'booty', 'bosom', 'bosomy', 'boy', 'boys', 'bra', 'brassiere', 'breast', 'breasts',
  'brown', 'brownie', 'bugger', 'buggery', 'bull', 'bulldike', 'bullshit', 'bully',
  'bunchofassholes', 'bum', 'bumblefuck', 'bumfuck', 'bunga', 'bunghole', 'butch',
  'butt', 'buttface', 'buttfuck', 'buttfucker', 'buttfuckers', 'butthead', 'butthole',
  'buttplug', 'buttstain', 'byatch', 'cacker', 'cameltoe', 'camgirl', 'cams', 'canadian',
  'cancer', 'carpetmuncher', 'carruth', 'catholic', 'catholics', 'cemetery',
  'chav', 'cherry', 'chick', 'chicks', 'chinese', 'chink', 'chinky', 'choad', 'chode',
  'christ', 'christian', 'church', 'cigarette', 'cigs', 'clam', 'clit', 'clitoris',
  'clits', 'clusterfuck', 'cocaine', 'cock', 'cockblock', 'cockblocker', 'cockcowboy',
  'cockfight', 'cockhead', 'cockknob', 'cockmaster', 'cockmongler', 'cockmongruel',
  'cockmuncher', 'cocknob', 'cocknose', 'cocknugget', 'cockshit', 'cocksmith',
  'cocksmoke', 'cocksmoker', 'cocksucker', 'cocksuckers', 'cocksucking', 'cocktease',
  'cocky', 'coffin', 'coon', 'cooner', 'coonass', 'coondog', 'cornhole', 'corruption',
  'crappy', 'crap', 'creampie', 'cretin', 'crime', 'crimes', 'criminal', 'criminals',
  'crotch', 'cum', 'cumfest', 'cumjockey', 'cumming', 'cunnilingus', 'cunt', 'cuntface',
  'cunthole', 'cuntlicker', 'cunts', 'dago', 'dahmer', 'dammit', 'damn', 'damned',
  'damnit', 'darkie', 'darn', 'daserk', 'dead', 'deaf', 'death', 'defecate', 'dego',
  'demon', 'deposit', 'desire', 'destroy', 'deth', 'devil', 'diarrhea', 'dick',
  'dickbag', 'dickbeaters', 'dickface', 'dickfuck', 'dickfucker', 'dickhead', 'dickhole',
  'dickjuice', 'dickmilk', 'dickmonger', 'dicks', 'dickslap', 'dicksucker', 'dicksucking',
  'dicktickler', 'dickwad', 'dickweasel', 'dickweed', 'dickwod', 'dike', 'dildo', 'dildos',
  'dink', 'dipshit', 'dipstick', 'dirty', 'disease', 'diseases', 'do-do', 'doggie-style',
  'doggystyle', 'dominatrix', 'doofus', 'dope', 'douche', 'douchebag', 'douche-fag', 'dripdick',
  'drug', 'drugs', 'drunk', 'drunken', 'dumb', 'dumbass', 'dumbbitch', 'dumbfuck', 'dyke',
  'dykes', 'ejaculate', 'enema', 'excite', 'erection', 'erotic', 'essohbee', 'execution',
  'executioner', 'exorcism', 'fag', 'faggit', 'faggot', 'faggots', 'faggy', 'fagtard', 'fail',
  'failure', 'fairies', 'fairy', 'faith', 'fannyfucker', 'fart', 'farted', 'farting', 'farty',
  'fastfuck', 'fat', 'fatass', 'fatfuck', 'fatfucker', 'fatso', 'fck', 'fcker', 'fckr',
  'fecal', 'felch', 'felcher', 'felching', 'fellatio', 'feltch', 'female', 'females',
  'fetish', 'fight', 'filipina', 'filipino', 'fingerfood', 'fingerfuck', 'fingerfucked',
  'fingerfucker', 'fingerfuckers', 'fingerfucking', 'fist', 'fisted', 'fistfuck', 'fistfucked',
  'fistfucker', 'fistfuckers', 'fistfucking', 'fisting', 'flange', 'flasher', 'flatulence',
  'floo', 'flusher', 'flydie', 'flydye', 'fok', 'fondle', 'footaction', 'footjob', 'footlicker',
  'foreskin', 'fornicate', 'foursome', 'fourtwenty', 'fraud', 'freak', 'freaky', 'freefuck',
  'freex', 'french', 'frenchie', 'frenchy', 'frick', 'frigg', 'frotting', 'fuck', 'fuckass',
  'fuckbag', 'fuckboy', 'fuckbrain', 'fuckbutt', 'fuckbutter', 'fucked', 'fucker', 'fuckers',
  'fuckersucker', 'fuckface', 'fuckfest', 'fuckfreak', 'fuckfriend', 'fuckhead', 'fuckher',
  'fuckhole', 'fuckin', 'fucking', 'fuckina', 'fuckingbitch', 'fuckme', 'fuckmehard', 'fuckmeharder',
  'fuckmehardest', 'fuckmeplease', 'fuckmetillicry', 'fuckoff', 'fuckpig', 'fucks', 'fucktard',
  'fuckwhore', 'fuckyou', 'fudgepacker', 'fugly', 'funfuck', 'fungus', 'funky', 'gai', 'gangbang',
  'gangbanged', 'gangbanger', 'gang-bang', 'gatorbait', 'gay', 'gayass', 'gaybob', 'gayboy',
  'gaydo', 'gayfuck', 'gayfuckist', 'gaylord', 'gays', 'gaysex', 'gaytard', 'gaywad', 'gaywads',
  'genital', 'genitalia', 'genitals', 'german', 'getiton', 'gfy', 'gi', 'giantcock', 'gigolo',
  'gin', 'ginzo', 'gipp', 'girl', 'girls', 'g-spot', 'god', 'godammit', 'goddamit', 'goddammit',
  'goddamn', 'goddamned', 'god-damned', 'godfucking', 'godsdamn', 'gook', 'gookeye', 'gooks',
  'gora', 'goregasm', 'gringo', 'groe', 'groid', 'gross', 'groupsex', 'gspot', 'guido', 'gummer',
  'gun', 'gyp', 'gypo', 'gypp', 'gyppo', 'gyppy', 'ham', 'handjob', 'hapa', 'hardon', 'harem',
  'headfuck', 'hebe', 'heeb', 'hell', 'hemp', 'henhouse', 'heroin', 'herpes', 'herpy', 'heshe',
  'hitler', 'hiv', 'ho', 'hoar', 'hoare', 'hobag', 'hoe', 'hoer', 'hoes', 'hole', 'holestuffer',
  'homo', 'homoerotic', 'homoey', 'homicide', 'homo', 'homosexual', 'honkey', 'honky', 'hooker',
  'hookers', 'hoor', 'hoore', 'hooters', 'hore', 'horny', 'horsecock', 'horseshit', 'hotcarl',
  'hotchick', 'hotsex', 'hottie', 'humping', 'hussy', 'hustler', 'hymen', 'hymie', 'iblowu',
  'idiot', 'ikey', 'illegal', 'incest', 'insest', 'intercourse', 'interracial', 'iran', 'iranian',
  'iraq', 'iraqi', 'irish', 'israel', 'israeli', 'italian', 'jackass', 'jackoff', 'jack-off',
  'jap', 'japcrap', 'jebus', 'jeez', 'jerk', 'jerkoff', 'jerk-off', 'jesuschrist', 'jesus-christ',
  'jew', 'jewboy', 'jewish', 'jig', 'jiga', 'jigaboo', 'jigg', 'jigga', 'jiggabo', 'jigger', 'jiggers',
  'jiggy', 'jihad', 'jijjiboo', 'jimfish', 'jism', 'jiz', 'jizm', 'jizz', 'jizzed', 'jock', 'jocky',
  'jocko', 'juggalo', 'juggs', 'junkie', 'junky', 'kafir', 'kike', 'kill', 'killer', 'killing', 'kink',
  'kinky', 'kiss', 'kkk', 'knockers', 'knob', 'knobjocky', 'kootch', 'kraut', 'kum', 'kumbubble',
  'kumbucket', 'kummer', 'kumming', 'kumshot', 'kums', 'kunilingus', 'kunt', 'kyke', 'lactating',
  'ladies', 'ladyboy', 'lame', 'lameo', 'lapdance', 'lesbian', 'lesbians', 'lesbo', 'lesbos',
  'lez', 'lezbian', 'lezbians', 'lezbo', 'lezbos', 'lezzie', 'lezzies', 'lezzy', 'limey',
  'limpdick', 'limy', 'lingerie', 'liquor', 'livesex', 'lmfao', 'loaded', 'loser', 'love',
  'lovebone', 'lovegoo', 'lovegun', 'lovejuice', 'lovemuscle', 'lovepistol', 'lover', 'loves',
  'lowlife', 'lsd', 'lust', 'lusting', 'lusty', 'macaca', 'mafia', 'magicwand', 'mahboud',
  'mams', 'manhater', 'manpiss', 'marijuana', 'masturbate', 'masturbating', 'masturbation',
  'mcfagget', 'meatbeater', 'meatrack', 'menageatrois', 'menses', 'menstruate', 'menstruation',
  'meth', 'mexican', 'mick', 'midget', 'milf', 'minge', 'missionary', 'mofo', 'molest',
  'molestation', 'mong', 'mongoloid', 'monster', 'monstercock', 'mormon', 'moron', 'motherfuck',
  'motherfucked', 'motherfucker', 'motherfuckers', 'motherfucking', 'motherfuckings', 'mound',
  'mrs', 'muff', 'muffdiver', 'muffpuff', 'murder', 'murderer', 'muslim', 'mutilate', 'mutilation',
  'muthafucker', 'muthafuckin', 'mutha', 'muther', 'naked', 'narcotic', 'nasty', 'nazi', 'necro',
  'negro', 'negroes', 'negroid', 'nig', 'niga', 'nigaboo', 'nigga', 'niggah', 'niggas',
  'niggaz', 'nigger', 'niggers', 'niggle', 'niglet', 'nig-nog', 'nipple', 'nipples', 'nob',
  'nobhead', 'nobjocky', 'nobjokey', 'nude', 'nudist', 'nudity', 'numbnuts', 'nutbutter',
  'nutsack', 'nympho', 'nymphomania', 'octopussy', 'omg', 'one-nightstand', 'opium', 'orafis',
  'orgasim', 'orgasims', 'orgasm', 'orgasms', 'orgies', 'orgy', 'osama', 'paddy', 'paedo',
  'paedophile', 'paki', 'pakistan', 'pakistani', 'panooch', 'pansy', 'panty', 'panties',
  'payo', 'pearlnecklace', 'pecker', 'peckerhead', 'peckerwood', 'pedo', 'pedophile',
  'pedophiliac', 'pee', 'pee-pee', 'pegging', 'penial', 'penile', 'penis', 'penises',
  'perv', 'perversion', 'pervert', 'phonesex', 'phuc', 'phuck', 'phuk', 'phuked',
  'phuking', 'phukked', 'phukking', 'phukme', 'phuks', 'phuq', 'pikey', 'pikey',
  'pimp', 'pimped', 'pimping', 'pimps', 'pinko', 'piss', 'pissed', 'pissedoff',
  'pisser', 'pisses', 'pissflaps', 'pissin', 'pissing', 'pissoff', 'pisspot', 'piss-pot',
  'pistol', 'playboy', 'playgirl', 'pleasure', 'pokey', 'pokie', 'polack', 'polak',
  'polish', 'polock', 'pony', 'poof', 'poon', 'poonani', 'poonany', 'poontang',
  'poop', 'poopchute', 'poop-chute', 'poopstain', 'porchmonkey', 'porn', 'porno',
  'pornography', 'pornos', 'pot', 'pothead', 'prick', 'pricks', 'prison', 'prostitute',
  'prostituted', 'prostitutes', 'prostituting', 'prude', 'psychopath', 'psycho', 'pubes',
  'pubic', 'pube', 'pubis', 'punk', 'punky', 'puss', 'pussies', 'pussy', 'pussyeating',
  'pussylips', 'pussylicker', 'pussypounder', 'pussys', 'pussywhipped', 'puto', 'queaf',
  'queef', 'queer', 'queerbait', 'queero', 'queers', 'queery', 'quicky', 'quim', 'racist',
  'raghead', 'ragingboner', 'rape', 'raped', 'raper', 'raping', 'rapist', 'raunch', 'rectal',
  'rectum', 'redneck', 'redskin', 'reefer', 'reestie', 'rentafuck', 'retard', 'retarded',
  'revenge', 'ricer', 'rimjob', 'rimming', 'ritard', 'rtard', 'rum', 'ruski', 'russian',
  'sadism', 'sadist', 'salope', 'sambo', 'sandnigger', 'satan', 'scag', 'scally', 'scank',
  'scat', 'schizo', 'schlong', 'screw', 'screwed', 'screwing', 'scrote', 'scrotum', 'scum',
  'seaman', 'seamen', 'seduce', 'seks', 'semen', 'sex', 'sexcam', 'sex-cam', 'sexfarm',
  'sexhound', 'sexing', 'sexkitten', 'sexpot', 'sexslave', 'sexting', 'sexual',
  'sexuality', 'sexually', 'sexvideo', 'sexy', 'shag', 'shagger', 'shaggin', 'shagging',
  'shat', 'she-male', 'shemale', 'shemales', 'shi', 'shibari', 'shit', 'shitass',
  'shitbag', 'shitbagger', 'shitbrains', 'shitbreath', 'shitcanned', 'shitcan',
  'shitcunt', 'shitdick', 'shite', 'shiteater', 'shited', 'shitey', 'shitface',
  'shitfaced', 'shitfit', 'shitforbrains', 'shitfuck', 'shitfucker', 'shitfull',
  'shithead', 'shithole', 'shithouse', 'shiting', 'shitlist', 'shitola', 'shitoutofluck',
  'shits', 'shitstain', 'shitted', 'shitter', 'shitters', 'shittiest', 'shitting',
  'shitty', 'shiz', 'shiznit', 'shortfuck', 'shota', 'shrimping', 'sissy', 'skag',
  'skank', 'skeet', 'skullfuck', 'slag', 'slant', 'slanteye', 'slave', 'slaves',
  'sleepy', 'slope', 'slopehead', 'slopey', 'slopy', 'slut', 'sluts', 'slutt', 'slutty',
  'smack', 'smegma', 'smut', 'smutty', 'snatch', 'sniper', 'snuff', 's-o-b', 'sodom',
  'sodomize', 'sodomy', 'sonofabitch', 'sonofbitch', 'son-of-a-bitch', 'spade',
  'spic', 'spick', 'spik', 'spiks', 'spooge', 'spook', 'sprog', 'spunk', 'spunkbubble',
  'spunkie', 'spunkjockey', 'spunks', 'spunky', 'squaw', 'stab', 'stiffy', 'stoned',
  'straight', 'straights', 'strap-on', 'strip', 'stripclub', 'stripper', 'stroking',
  'stupid', 'stupidfuck', 'stupidfucker', 'style', 'suck', 'suckass', 'sucked', 'sucker',
  'suckers', 'suckhole', 'suckin', 'sucking', 'sucks', 'suicide', 'sumofabiatch',
  'swastika', 'swinger', 'syphilis', 'taboo', 'tard', 'tart', 'tastemy', 'tawdry',
  'teabagging', 'teat', 'teats', 'teets', 'terror', 'terrorist', 'teste', 'testee',
  'testes', 'testical', 'testicle', 'testis', 'thai', 'threesome', 'throating',
  'thumbzilla', 'thundercunt', 'tim-ber', 'tinkle', 'tit', 'titbit', 'titfuck',
  'titfucker', 'titfuckin', 'titjob', 'titlicker', 'tits', 'tittie', 'tittiefucker',
  'titties', 'titty', 'tittyfuck', 'tittyfucker', 'tittywank', 'titwank', 'toke',
  'toots', 'topless', 'tosser', 'towelhead', 'trailer', 'trannie', 'tranny', 'trans',
  'transsexual', 'transvestite', 'trisexual', 'tuckahoe', 'tunneloflove', 'turd',
  'turnon', 'twat', 'twatlips', 'twats', 'twatwaffle', 'twink', 'twinkie', 'twunt',
  'ugly', 'uk', 'unclesame', 'unfuckable', 'uniballer', 'uptheass', 'upthebutt',
  'urinal', 'urine', 'urophilia', 'uterus', 'vagina', 'vaginal', 'valium', 'vatican',
  'vibrator', 'vietcong', 'vietnam', 'vietnamese', 'virgin', 'virginity', 'vodka',
  'vomit', 'voyeur', 'vulva', 'wad', 'wang', 'wank', 'wanker', 'wankers', 'wanking',
  'wankjob', 'wanky', 'wetback', 'wetdream', 'whigger', 'white', 'whitey', 'whities',
  'whiz', 'whore', 'whorebag', 'whoreface', 'whorefucker', 'whorehouse', 'whores',
  'wigger', 'willie', 'willy', 'winner', 'wog', 'wop', 'wuss', 'wuzzie', 'xtc', 'xxx',
  'yellowman', 'zigabo'
]);
